# 🧩 Avance 2: Diseño e Implementación del **Modelo Relacional**

## 📘 Consigna
En esta segunda fase del proyecto para **TechCore**, se diseña e implementa un **modelo relacional** a partir del dataset limpio (`ventasTransformed.csv`).  
El propósito es estructurar las tablas de manera que representen adecuadamente las relaciones entre las entidades del proceso de ventas, manteniendo la **integridad referencial**, la **normalización** y la **coherencia lógica** del modelo.

A diferencia de un esquema Copo de Nieve, el **modelo relacional** busca representar las entidades principales con sus claves primarias y foráneas, sin una descomposición excesiva de las dimensiones.

---

## 🏗️ Tablas a Construir

### **Tablas Dimensionales**
- 🏙️ **Ciudades**  
- 🏢 **Sucursales**  
- 👨‍💼 **Vendedores**  
- 👥 **Clientes**  
- 📦 **Productos**  
- 💳 **Métodos de Pago**

### **Tablas de Hechos**
- 🧾 **Facturas**  
- 📄 **DetalleFacturas**

### **Tablas Derivadas o de Análisis**
- ⭐ **Marcas más vendidas**  
- 🔝 **Productos más vendidos**

---

## 📊 Resultado Esperado
El resultado final será el archivo **`modeloVentas.xlsx`**, que contendrá todas las tablas del **modelo relacional** listas para su importación y modelado en **Power BI**, permitiendo analizar el desempeño de ventas, productos, clientes y sucursales de **TechCore**.

## 1.Carga de Datos

In [113]:
# CODE CELL 1: Importación de Librerías y Carga de Datos

import pandas as pd
import numpy as np
import io


# ==============================================================================
# 0. CONFIGURACIÓN E IMPORTACIÓN DE DATOS
# ==============================================================================

# Cargar el dataset limpio exportado desde Power Query.
# Utilizamos el delimitador ';' (punto y coma).
df_ventas = pd.read_csv(r'C:\Users\DODY DUEÑAS\Documents\Modulo 3\ProyectoVentas_Dody_Salim_Dueñas_Remache\Avance_1\ventasTransformed.csv', sep=';', encoding='latin-1')
print("Dataset 'ventasTransformed.csv' cargado exitosamente.")

Dataset 'ventasTransformed.csv' cargado exitosamente.

## 2. Generación de Tablas Dimensionales (DIM)

Se aplica la normalización extrayendo las entidades únicas del negocio y asignando una Clave Primaria (PK) autoincremental a cada dimensión.

###  Tabla de Ciudades

In [114]:
# CODE CELL 2: 1.1 Ciudades (DIM) - PK: CiudadID

# ------------------------------------------------------------------------------
# 1.1 Ciudades (Dim_Ciudades)
# ------------------------------------------------------------------------------
df_ciudades = df_ventas[['CiudadSucursal']].drop_duplicates().reset_index(drop=True)
df_ciudades = df_ciudades.rename(columns={'CiudadSucursal': 'NombreCiudad'})
# Generar la Clave Primaria (PK).
df_ciudades.insert(0, 'CiudadID', df_ciudades.index + 1)
df_ciudades.set_index('CiudadID', inplace=True)
print("Tabla Ciudades creada.")
df_ciudades

Tabla Ciudades creada.

         NombreCiudad
CiudadID
1             Pereíra
2            Medellín
3                Cali
4              Bogotá

## Tabla de Vendedores

In [115]:
# CODE CELL 3: 1.2 Vendedores (DIM) - PK: VendedorID

# ------------------------------------------------------------------------------
# 1.2 Vendedores (Dim_Vendedores)
# ------------------------------------------------------------------------------
df_vendedores = df_ventas[['VendedorNombre']].drop_duplicates().reset_index(drop=True)
# Generar la Clave Primaria (PK).
df_vendedores.insert(0, 'VendedorID', df_vendedores.index + 1)
df_vendedores.set_index('VendedorID', inplace=True)
print("Tabla Vendedores creada.")
df_vendedores

Tabla Vendedores creada.

                             VendedorNombre
VendedorID
1                    Amílcar Ortega-Alberto
2                 Ana Sofía Llopis Blázquez
3                    Juan José Porcel-Riera
4                      Jacinta Juárez Marín
5                  Clímaco Salinas Zabaleta
6                    Carina Parejo Carranza
7                          Edu Juan Pedraza
8                       Armida Azorin Plaza
9                   Rosendo Barberá Cordero
10                 Herminia Meléndez-Huguet
11          Almudena Adelaida Lledó Garrido
12                 Jose Angel Rovira Adadia
13                      Eusebia Jara Macias
14                   Basilio Marcos Barrena
15                       Olivia Armas Ayuso
16                       Ibán López Córdoba
17                   Liliana Jordá Armengol
18                María Belén Alegria Camps
19                        Aura del Bermúdez
20                    Evaristo Guillen Peña
21                             Luisina Lasa
22                             Juanito Diaz
23                     Eloísa Plaza Hurtado
24                Poncio Gabriel Poza Acedo
25                    Dominga del Alcántara
26                  Anacleto Morera Segovia
27                  Griselda Arnaiz Palacio
28                  Claudia Sastre-Quintero
29                        María Ramírez Pou
30                Florencio Iker Vara Nebot

## Tabla de Clientes

In [116]:
# CODE CELL 4: 1.3 Clientes (DIM) - PK: ClienteID

# ------------------------------------------------------------------------------
# 1.3 Clientes (Dim_Clientes)
# ------------------------------------------------------------------------------
# Columnas que definen un cliente único.
cliente_cols = ['Cliente_Nombre', 'GeneroCliente', 'edadcliente', 'EmailCliente', 'TelefonoCliente', 'Direccion_Cliente']
df_clientes = df_ventas[cliente_cols].drop_duplicates().reset_index(drop=True)
# Generar la Clave Primaria (PK).
df_clientes.insert(0, 'ClienteID', df_clientes.index + 1)
df_clientes.set_index('ClienteID', inplace=True)
print("Tabla Clientes creada.")
df_clientes

Tabla Clientes creada.

,Cliente_Nombre,GeneroCliente,edadcliente,EmailCliente,TelefonoCliente,Direccion_Cliente
ClienteID,,,,,,
1,Bienvenida Nebot-Fiol,F,37,bienvenida19@hotmail.com,34806548767,cll 52 #32-98
2,Teófila Bueno-Novoa,F,43,teófila35@gmail.com,+34 947255990,cll 96 #81-94
3,Gilberto Chamorro Catalá,M,38,gilberto57@hotmail.com,+34 978 810 249,cra 28 #79-85
4,Máximo Coronado Huerta,M,30,máximo65@hotmail.com,+34 825429634,cll 5 #89-26
5,Yago Oliver,M,51,yago38@yahoo.com,34988285275,cra 32 #97-86
...,...,...,...,...,...,...
17449,Jose Miguel Rosa Arenas,M,26,jose32@yahoo.com,+34 744 79 73 83,cll 32 #35-85
17450,Manolo Lerma,M,41,manolo78@hotmail.com,+34 627546892,cll 27 #59-20
17451,Ildefonso Abad Amigó,M,26,ildefonso41@yahoo.com,+34 977633270,cra 14 #68-3
17452,Gabriel Cristian Zamora Artigas,M,50,No especificado,+34885 996 094,cll 46 #62-87
17453,Paco Olivera Suárez,M,36,paco25@hotmail.com,34976445455,cra 45 #49-2

## Tabla de Sucursales

In [117]:
# CODE CELL 5: 1.4 Sucursales (DIM) - PK: SucursalID, FK: CiudadID

# ------------------------------------------------------------------------------
# 1.4 Sucursales (Dim_Sucursales) - Relación Copo de Nieve (Snowflake)
# ------------------------------------------------------------------------------
df_sucursales = df_ventas[['SucursalNombre', 'CiudadSucursal']].drop_duplicates().reset_index(drop=True)
df_sucursales.insert(0, 'SucursalID', df_sucursales.index + 1)

# Añadir la Clave Foránea (FK) 'CiudadID' mediante JOIN.
df_sucursales = pd.merge(df_sucursales, df_ciudades.reset_index(),
                         left_on='CiudadSucursal', right_on='NombreCiudad', how='left')
# Seleccionar las columnas finales: PK, Nombre, FK.
df_sucursales = df_sucursales[['SucursalID', 'SucursalNombre', 'CiudadID']]
df_sucursales.set_index('SucursalID', inplace=True)
print("Tabla Sucursales creada (normalizada con FK a Ciudades).")
df_sucursales

Tabla Sucursales creada (normalizada con FK a Ciudades).

                  SucursalNombre  CiudadID
SucursalID
1               TechCore Pereíra         1
2           TechCore Medellín #1         2
3           TechCore Medellín #2         2
4                  TechCore Cali         3
5             TechCore Bogotá #2         4
6             TechCore Bogotá #1         4

## Tabla de Productos

In [118]:
# CODE CELL 6: 1.5 Productos (DIM) - PK: ProductoID

# ------------------------------------------------------------------------------
# 1.5 Productos (Dim_Productos)
# ------------------------------------------------------------------------------
# Se desnormalizan y apilan las 3 columnas de producto en una lista maestra.
productos_data = []
for i in range(1, 4):
    cols = [f'Producto{i}Nombre', f'Producto{i}Marca', f'Producto{i}PrecioUnitario']
    temp_df = df_ventas[cols].copy()
    temp_df.columns = ['NombreProducto', 'MarcaProducto', 'PrecioUnitario']
    productos_data.append(temp_df.dropna(subset=['NombreProducto']))

df_productos_raw = pd.concat(productos_data).drop_duplicates()
# Consolidar productos por Nombre y Marca.
df_productos = df_productos_raw.groupby(['NombreProducto', 'MarcaProducto']).agg({
    'PrecioUnitario': 'first'
}).reset_index()

# Generar la Clave Primaria (PK).
df_productos.insert(0, 'ProductoID', df_productos.index + 1)
df_productos.set_index('ProductoID', inplace=True)
print("Tabla Productos creada.")
df_productos

Tabla Productos creada.

                         NombreProducto MarcaProducto  PrecioUnitario
ProductoID
1                         Acer Aspire 5          Acer         2000000
2                          Acer Nitro 5          Acer         4000000
3              Acer Predator Helios 300          Acer         5600000
4                          Acer Swift 3          Acer         2600000
5                  Apple MacBook Air M1         Apple         5500000
6                  Apple MacBook Pro 14         Apple         8000000
7                  Apple MacBook Pro 16         Apple         9600000
8                         Apple iMac 24         Apple         6400000
9                    Asus ROG Strix G15          Asus         6400000
10                  Asus TUF Gaming A15          Asus         4800000
11                     Asus VivoBook 15          Asus         2400000
12                      Asus ZenBook 14          Asus         3800000
13                   Dell Alienware m15          Dell         8000000
14                     Dell Inspiron 15          Dell         3000000
15                   Dell Latitude 7420          Dell         5600000
16                          Dell XPS 13          Dell         4800000
17                  Delll Alienware m15          Dell        80000000
18                    Delll Inspiron 15          Dell        30000000
19                  Delll Latitude 7420          Dell        56000000
20                         Delll XPS 13          Dell        48000000
21                           HP Envy 13            HP         4000000
22                           HP Omen 16            HP         6000000
23                       HP Pavilion 15            HP         3500000
24                      HP Spectre x360            HP         5200000
25                     Lenovo IdeaPad 5        Lenovo         2800000
26                  Lenovo Legion 5 Pro        Lenovo         7200000
27            Lenovo ThinkPad X1 Carbon        Lenovo         6800000
28                       Lenovo Yoga 7i        Lenovo         4400000
29                      MSI GE76 Raider           MSI        10000000
30                        MSI GF65 Thin           MSI         4400000
31                     MSI GS66 Stealth           MSI         8000000
32                        MSI Modern 14           MSI         2800000
33             Microsoft Surface Book 3     Microsoft         6400000
34               Microsoft Surface Go 3     Microsoft         3000000
35           Microsoft Surface Laptop 4     Microsoft         5200000
36              Microsoft Surface Pro 9     Microsoft         4400000
37                       Razer Blade 15         Razer         8800000
38                       Razer Blade 15         Razor        88000000
39                       Razer Blade 17         Razer        10000000
40                       Razer Blade 17         Razor       100000000
41               Razer Blade Stealth 13         Razer         7200000
42               Razer Blade Stealth 13         Razor        72000000
43                        Razer Book 13         Razer         6400000
44                        Razer Book 13         Razor        64000000
45             Samsung Galaxy Book Flex       Samsung         5600000
46          Samsung Galaxy Book Odyssey       Samsung         6800000
47              Samsung Galaxy Book Pro       Samsung         4800000
48          Samsung Galaxy Chromebook 2       Samsung         2000000

## Tabla de Métodos de Pago

In [119]:
# ------------------------------------------------------------------------------
# 1.6 Métodos de Pago (Dim_MetodosPago)
# ------------------------------------------------------------------------------
# Extrae los valores únicos de la columna 'MetodoPago' para crear la tabla maestra.
metodos_pago_unicos = df_ventas['MetodoPago'].unique()

# Crea el DataFrame de la Dimensión
df_metodos_pago = pd.DataFrame({
    'MetodoPagoID': range(1, len(metodos_pago_unicos) + 1),
    'TipoMetodoPago': metodos_pago_unicos
})
df_metodos_pago.set_index('MetodoPagoID', inplace=True) # Mantenemos el PK como índice en Pandas

print("Tabla 1: Métodos de Pago (Dimensión)")
# Corrección: Dejamos la variable sola para que Jupyter use su formato de impresión con el índice PK
df_metodos_pago

Tabla 1: Métodos de Pago (Dimensión)

                 TipoMetodoPago
MetodoPagoID
1               Tarjeta Crédito
2             Billetera Digital
3                Tarjeta Débito
4                 Transferencia
5               No especificado
6                      Efectivo

## 3. Generación de Tablas de Hechos (Fact)

Se crean las tablas transaccionales Facturas (cabecera) y DetalleFacturas (líneas), mapeando las dimensiones a través de las Claves Foráneas (FKs).

## Tabla de Facturas

In [120]:
# ------------------------------------------------------------------------------
# 2.1 Facturas (Fact_Facturas) - PK: FacturaID, FKs: MetodoPagoID sin _FK
# ------------------------------------------------------------------------------
# Inicializar la tabla de hechos con la cabecera de la venta.
df_facturas = df_ventas.copy().rename(columns={'VentaID': 'FacturaID'})

# Estandarizar nombres de columnas para evitar errores de codificación (ñ, tildes, etc.)
# IMPORTANTE: Eliminada la conversión de 'AñoVenta' a 'AnioVenta'.
import unicodedata
df_facturas.columns = [unicodedata.normalize('NFKC', c).replace('ń', 'ñ') for c in df_facturas.columns]

# Mapear Claves Foráneas (FKs) desde las dimensiones:

# 1. Vendedor
df_facturas = pd.merge(df_facturas, df_vendedores.reset_index(), on='VendedorNombre', how='left')

# 2. Cliente
cliente_map_cols = [
    'Cliente_Nombre', 'GeneroCliente', 'edadcliente',
    'EmailCliente', 'TelefonoCliente', 'Direccion_Cliente'
]
df_facturas = pd.merge(
    df_facturas,
    df_clientes.reset_index()[['ClienteID'] + cliente_map_cols],
    on=cliente_map_cols,
    how='left'
)

# 3. Sucursal
df_facturas = pd.merge(
    df_facturas,
    df_sucursales.reset_index()[['SucursalID', 'SucursalNombre']],
    on='SucursalNombre',
    how='left'
)

# 4. MetodoPago (Mapear y añadir MetodoPagoID)
df_facturas = pd.merge(
    df_facturas,
    df_metodos_pago.reset_index(), # Usa la tabla de dimensión
    left_on='MetodoPago',
    right_on='TipoMetodoPago',
    how='left'
)


# --- RENOMBRADO FINAL DE FKs SIN SUFIJO '_FK' ---
df_facturas.rename(columns={
    'VendedorID': 'VendedorID',     # VendedorID (PK) se convierte en VendedorID (FK)
    'ClienteID': 'ClienteID',       # ClienteID (PK) se convierte en ClienteID (FK)
    'SucursalID': 'SucursalID',     # SucursalID (PK) se convierte en SucursalID (FK)
    'MetodoPagoID': 'MetodoPagoID' # MetodoPagoID (PK) se convierte en MetodoPagoID (FK)
}, inplace=True)


# Seleccionar las columnas finales de la cabecera.
# El nombre 'AñoVenta' se mantiene tal como está en el DataFrame original.
facturas_cols_final = [
    'FacturaID', 'FechaVenta', 'HoraVenta',
    'SucursalID', 'ClienteID', 'VendedorID',
    'MetodoPagoID', 
    'DescuentoVenta', 'TotalVenta', 'MesVenta', 'MesNumero', 'AñoVenta' # <-- 'AñoVenta' REESTABLECIDO
]

# Selección final de columnas y configuración de índice
# Seleccionamos solo las columnas que existen después de todos los merges.
df_facturas = df_facturas[[c for c in facturas_cols_final if c in df_facturas.columns]]
df_facturas.set_index('FacturaID', inplace=True)

print("Tabla Facturas (Cabecera) creada correctamente con 'AñoVenta'.")
df_facturas

Tabla Facturas (Cabecera) creada correctamente con 'AñoVenta'.

,FechaVenta,HoraVenta,SucursalID,ClienteID,VendedorID,MetodoPagoID,DescuentoVenta,TotalVenta,MesVenta,MesNumero,AñoVenta
FacturaID,,,,,,,,,,,
1,"jueves, 31 de diciembre de 2015",5:42:43,1,1,1,1,0,312000000,diciembre,12,2015
2,"sábado, 23 de marzo de 2019",19:03:21,2,2,2,2,0,108000000,marzo,3,2019
3,"domingo, 23 de diciembre de 2018",2:32:34,3,3,3,3,0,219000000,diciembre,12,2018
4,"sábado, 14 de noviembre de 2015",0:37:36,3,4,3,2,0,136000000,noviembre,11,2015
5,"martes, 29 de noviembre de 2016",10:34:20,4,5,4,1,0,139000000,noviembre,11,2016
...,...,...,...,...,...,...,...,...,...,...,...
29996,"jueves, 31 de diciembre de 2020",1:33:17,3,14207,3,1,0,68000000,diciembre,12,2020
29997,"viernes, 14 de julio de 2017",11:29:20,4,1586,14,1,0,264000000,julio,7,2017
29998,"sábado, 6 de abril de 2019",21:38:27,3,17453,28,4,0,56000000,abril,4,2019
29999,"viernes, 27 de diciembre de 2024",6:49:00,2,7089,25,4,0,108000000,diciembre,12,2024
30000,"miércoles, 23 de marzo de 2022",18:41:51,6,526,24,4,5,90250000,marzo,3,2022

## Tabla de Detalles de Facturas

In [121]:
# CODE CELL 8: 2.2 DetalleFacturas (FACT Detail)

# ------------------------------------------------------------------------------
# 2.2 DetalleFacturas (Fact_DetalleFacturas) - PK: DetalleID, FKs: FacturaID, ProductoID
# ------------------------------------------------------------------------------
detalle_data = []
# Desnormalización de las líneas de detalle (se crea una fila por cada producto vendido).
for i in range(1, 4):
    cols = [
        'VentaID', f'Producto{i}Nombre', f'Producto{i}Marca',
        f'Producto{i}Cantidad', f'Producto{i}PrecioUnitario', f'Producto{i}Subtotal'
    ]
    temp_df = df_ventas.dropna(subset=[f'Producto{i}Nombre'])[cols].copy()
    temp_df.columns = ['FacturaID', 'NombreProducto', 'MarcaProducto', 'Cantidad', 'PrecioUnitario', 'Subtotal']
    detalle_data.append(temp_df)

df_detalle_facturas = pd.concat(detalle_data, ignore_index=True)

# Mapeo de ProductoID (FK) uniendo con la dimensión Productos.
df_detalle_facturas = pd.merge(df_detalle_facturas, df_productos.reset_index()[['ProductoID', 'NombreProducto', 'MarcaProducto']],
                               on=['NombreProducto', 'MarcaProducto'], how='left')

# Generar DetalleID (PK) para cada línea transaccional.
df_detalle_facturas.insert(0, 'DetalleID', df_detalle_facturas.index + 1)
# Seleccionar las columnas finales (PK, FKs y métricas).
detalle_facturas_cols = [
    'DetalleID', 'FacturaID', 'ProductoID', 'Cantidad', 'PrecioUnitario', 'Subtotal'
]
df_detalle_facturas = df_detalle_facturas[detalle_facturas_cols]
df_detalle_facturas.set_index('DetalleID', inplace=True)
print("Tabla DetalleFacturas (Línea) creada.")
df_detalle_facturas

Tabla DetalleFacturas (Línea) creada.

           FacturaID  ProductoID  Cantidad  PrecioUnitario  Subtotal
DetalleID
1                  1           7         1         9600000   9600000
2                  2           2         1         4000000   4000000
3                  3          15         2         5600000  11200000
4                  4          10         1         4800000   4800000
5                  5          24         1         5200000   5200000
...              ...         ...       ...             ...       ...
60055          29986           6        10        80000000  80000000
60056          29988          28        10        44000000  44000000
60057          29991          25        10        28000000  28000000
60058          29994           1        20        20000000  40000000
60059          29997          10        10        48000000  48000000

[60059 rows x 5 columns]

## 4. Verificación de Consistencia y Control de Calidad

Se generan los reportes exploratorios solicitados para validar que el modelo relacional funciona correctamente y los datos son consistentes.

In [122]:
# CODE CELL 9: Generación de Reportes

# ------------------------------------------------------------------------------
# 3.1 Reporte: Total de ventas por marca.
# ------------------------------------------------------------------------------
df_ventas_por_marca = pd.merge(df_detalle_facturas.reset_index(), df_productos.reset_index()[['ProductoID', 'MarcaProducto']], on='ProductoID', how='left')
df_ventas_por_marca = df_ventas_por_marca.groupby('MarcaProducto')['Subtotal'].sum().sort_values(ascending=False).to_frame(name='TotalVentas').reset_index()

# ------------------------------------------------------------------------------
# 3.2 Reporte: Top 10 productos más vendidos (por cantidad).
# ------------------------------------------------------------------------------
df_productos_vendidos = pd.merge(df_detalle_facturas.reset_index(), df_productos.reset_index()[['ProductoID', 'NombreProducto', 'MarcaProducto']], on='ProductoID', how='left')
df_top_productos = df_productos_vendidos.groupby(['NombreProducto', 'MarcaProducto'])['Cantidad'].sum().sort_values(ascending=False).head(10).to_frame(name='CantidadTotalVendida').reset_index()

print("\n--- Resultados de los Reportes de Consistencia ---")
print("\nTotal de ventas por marca:")
print(df_ventas_por_marca.to_markdown(index=False))
print("\nTop 10 productos más vendidos (por cantidad):")
print(df_top_productos.to_markdown(index=False))

--- Resultados de los Reportes de Consistencia ---

Total de ventas por marca:
| MarcaProducto   |   TotalVentas |
|:----------------|--------------:|
| Lenovo          |  656165600000 |
| HP              |  529810000000 |
| Dell            |  476146600000 |
| Apple           |  422534400000 |
| Asus            |  182941400000 |
| Acer            |  121788800000 |
| Samsung         |   67596000000 |
| MSI             |   47754400000 |
| Microsoft       |   45193600000 |
| Razer           |   19174800000 |
| Razor           |    3100000000 |

Top 10 productos más vendidos (por cantidad):
| NombreProducto            | MarcaProducto   |   CantidadTotalVendida |
|:--------------------------|:----------------|-----------------------:|
| HP Spectre x360           | HP              |                  41350 |
| Lenovo ThinkPad X1 Carbon | Lenovo          |                  32724 |
| Lenovo Legion 5 Pro       | Lenovo          |                  32033 |
| Lenovo Yoga 7i            | Lenovo          |                  28605 |
| HP Omen 16                | HP              |                  27781 |
| Lenovo IdeaPad 5          | Lenovo          |                  27551 |
| HP Pavilion 15            | HP              |                  22488 |
| Dell Latitude 7420        | Dell            |                  17730 |
| Apple MacBook Air M1      | Apple           |                  17664 |
| HP Envy 13                | HP              |                  17349 |

## Tablas Derivadas o de Análisis

## Productos más vendidos

In [123]:
# -------------------------------------------------------------------
# --- 2. Preparación de Datos (Reestructuración/Unpivot) ---
# Necesitamos una sola columna de 'ProductoNombre', 'Marca', y 'Cantidad'
# para poder hacer las sumas de ventas correctamente.

# 1. Extraer y renombrar los datos para cada Producto (Producto 1, 2 y 3)
productos1 = df_ventas[['VentaID', 'Producto1Nombre', 'Producto1Marca', 'Producto1Cantidad']].copy()
productos1.columns = ['VentaID', 'ProductoNombre', 'Marca', 'Cantidad']

productos2 = df_ventas[['VentaID', 'Producto2Nombre', 'Producto2Marca', 'Producto2Cantidad']].copy()
productos2.columns = ['VentaID', 'ProductoNombre', 'Marca', 'Cantidad']

productos3 = df_ventas[['VentaID', 'Producto3Nombre', 'Producto3Marca', 'Producto3Cantidad']].copy()
productos3.columns = ['VentaID', 'ProductoNombre', 'Marca', 'Cantidad']

# 2. Unir (Concatenar) los tres DataFrames en uno solo
df_productos_vendidos = pd.concat([productos1, productos2, productos3], ignore_index=True)

# 3. Limpiar: Filtrar filas donde la Cantidad es 0 o donde el ProductoNombre es nulo
df_productos_vendidos = df_productos_vendidos[df_productos_vendidos['Cantidad'] > 0].dropna(subset=['ProductoNombre', 'Marca'])

In [124]:
# -------------------------------------------------------------------
# --- 3. Creación de la Vista: Productos más vendidos (Análisis) ---

# 1. Agrupar por el nombre del producto y sumar la cantidad vendida.
df_prod_vendidos_view = df_productos_vendidos.groupby('ProductoNombre')['Cantidad'].sum().reset_index()
df_prod_vendidos_view.rename(columns={'Cantidad': 'TotalUnidadesVendidas'}, inplace=True)

# 2. Ordenar por la cantidad vendida y generar el ranking.
df_prod_vendidos_view = df_prod_vendidos_view.sort_values(by='TotalUnidadesVendidas', ascending=False)
df_prod_vendidos_view['Ranking'] = df_prod_vendidos_view['TotalUnidadesVendidas'].rank(method='min', ascending=False).astype(int)

# 3. Seleccionar y reordenar las columnas finales.
df_prod_vendidos_view = df_prod_vendidos_view[['Ranking', 'ProductoNombre', 'TotalUnidadesVendidas']]

print("\n Tabla: Productos más vendidos")
df_prod_vendidos_view

 Tabla: Productos más vendidos

    Ranking               ProductoNombre  TotalUnidadesVendidas
23        1              HP Spectre x360                  41350
26        2    Lenovo ThinkPad X1 Carbon                  32724
25        3          Lenovo Legion 5 Pro                  32033
27        4               Lenovo Yoga 7i                  28605
21        5                   HP Omen 16                  27781
24        6             Lenovo IdeaPad 5                  27551
22        7               HP Pavilion 15                  22488
14        8           Dell Latitude 7420                  17730
4         9         Apple MacBook Air M1                  17664
20       10                   HP Envy 13                  17349
15       11                  Dell XPS 13                  16922
5        12         Apple MacBook Pro 14                  16674
3        13                 Acer Swift 3                  13920
10       14             Asus VivoBook 15                  13799
12       15           Dell Alienware m15                  13579
13       16             Dell Inspiron 15                  13557
11       17              Asus ZenBook 14                  13261
0        18                Acer Aspire 5                  13098
7        19                Apple iMac 24                  12357
6        20         Apple MacBook Pro 16                  11761
9        21          Asus TUF Gaming A15                   9099
8        22           Asus ROG Strix G15                   8712
19       23                 Delll XPS 13                   7890
18       24          Delll Latitude 7420                   7180
1        25                 Acer Nitro 5                   6551
16       26          Delll Alienware m15                   6360
2        27     Acer Predator Helios 300                   5928
17       28            Delll Inspiron 15                   5790
40       29     Samsung Galaxy Book Flex                   4255
42       30      Samsung Galaxy Book Pro                   4082
43       31  Samsung Galaxy Chromebook 2                   3118
34       32   Microsoft Surface Laptop 4                   2912
35       33      Microsoft Surface Pro 9                   2865
41       34  Samsung Galaxy Book Odyssey                   2638
29       35                MSI GF65 Thin                   2302
30       36             MSI GS66 Stealth                   2208
32       37     Microsoft Surface Book 3                   1868
33       38       Microsoft Surface Go 3                   1830
28       39              MSI GE76 Raider                   1577
31       40                MSI Modern 14                   1497
37       41               Razer Blade 17                    743
39       42                Razer Book 13                    677
36       43               Razer Blade 15                    666
38       44       Razer Blade Stealth 13                    646

## Marcas mas Vendidas

In [125]:
# -------------------------------------------------------------------
# --- 4. Creación de la Vista: Marcas más vendidas (Análisis) ---

# 1. Agrupar la tabla de ventas "plana" por la Marca y sumar la cantidad vendida.
df_marcas_vendidas_view = df_productos_vendidos.groupby('Marca')['Cantidad'].sum().reset_index()
df_marcas_vendidas_view.rename(columns={'Cantidad': 'TotalUnidadesVendidas'}, inplace=True)

# 2. Ordenar por la cantidad vendida y generar el ranking.
df_marcas_vendidas_view = df_marcas_vendidas_view.sort_values(by='TotalUnidadesVendidas', ascending=False)
df_marcas_vendidas_view['Ranking'] = df_marcas_vendidas_view['TotalUnidadesVendidas'].rank(method='min', ascending=False).astype(int)

# 3. Seleccionar y reordenar las columnas finales.
df_marcas_vendidas_view = df_marcas_vendidas_view[['Ranking', 'Marca', 'TotalUnidadesVendidas']]

print("Tabla: Marcas más vendidas (Análisis/Vista)")
df_marcas_vendidas_view

Tabla: Marcas más vendidas (Análisis/Vista)

    Ranking      Marca  TotalUnidadesVendidas
5         1     Lenovo                 120913
4         2         HP                 108968
3         3       Dell                  89008
1         4      Apple                  58456
2         5       Asus                  44871
0         6       Acer                  39497
10        7    Samsung                  14093
7         8  Microsoft                   9475
6         9        MSI                   7584
8        10      Razer                   2342
9        11      Razor                    390

## Exportación a Excel

In [127]:
# ------------------------------------------------------------------------------
# 4. EXPORTACIÓN DEL MODELO FINAL (Corregida a 8 Tablas Base para Power BI)
# ------------------------------------------------------------------------------

# Se agrupan las 8 Tablas Base del Modelo Relacional (Hechos y Dimensiones)
# NOTA: df_marcas se ha EXCLUIDO de este diccionario, como solicitaste.
dataframes_base_model = {
    'Facturas': df_facturas.reset_index(drop=False), # Exporta FacturaID
    'DetalleFacturas': df_detalle_facturas.reset_index(drop=False), # Exporta DetalleID
    'Productos': df_productos.reset_index(drop=False), # Exporta ProductoID
    'Clientes': df_clientes.reset_index(drop=False), # Exporta ClienteID
    'Vendedores': df_vendedores.reset_index(drop=False), # Exporta VendedorID
    'Sucursales': df_sucursales.reset_index(drop=False), # Exporta SucursalID
    'Ciudades': df_ciudades.reset_index(drop=False), # Exporta CiudadID
    'MetodosPago': df_metodos_pago.reset_index(drop=False) # Exporta MetodoPagoID
}

# Crear el archivo Excel 'modeloVentas.xlsx' con cada DataFrame como una hoja.
with pd.ExcelWriter('modeloVentas.xlsx', engine='xlsxwriter') as writer:
    
    # Exportar las 8 Tablas Base del Modelo Relacional
    for sheet_name, df in dataframes_base_model.items():
        # Exportar sin el índice de pandas (pero incluyendo la columna PK).
        df.to_excel(writer, sheet_name=sheet_name, index=False)
        
    # Exportar las 2 Tablas de Análisis/Vistas en hojas separadas
    # Estas vistas utilizan df_marcas, pero se exportan separadamente.
    df_prod_vendidos_view.to_excel(writer, sheet_name='ProductosMasVendidos', index=False)
    df_marcas_vendidas_view.to_excel(writer, sheet_name='MarcasMasVendidas', index=False)
    

print("\n------------------------------------------------------------------")
print("PROCESO DE MODELADO Y EXPORTACIÓN FINALIZADO.")
print("Archivo 'modeloVentas.xlsx' generado con las 8 tablas base del Modelo Relacional y 2 Vistas de Análisis.")
print("Las claves primarias/foráneas están correctamente formateadas para Power BI.")
print("------------------------------------------------------------------")

------------------------------------------------------------------
PROCESO DE MODELADO Y EXPORTACIÓN FINALIZADO.
Archivo 'modeloVentas.xlsx' generado con las 8 tablas base del Modelo Relacional y 2 Vistas de Análisis.
Las claves primarias/foráneas están correctamente formateadas para Power BI.
------------------------------------------------------------------